name: rmwlog
description: simple log , can custom log output function
version: 1.0.4
homepage: https://github.com/rmw-dart/rmwlog

environment:
  sdk: '>=2.14.3 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  stack_trace: ^1.10.0

